---
- name: Deploy repo for CRI-O
  template:
    src: "{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - crio.repo

- name: Install pkgs for CRI-O
  yum:
    name:
      - cri-o
    state: present
    update_cache: yes
  register: crio

- name: Delete all cni configuration
  shell: rm -f /etc/cni/net.d/*
  when: crio.changed

- name: Deploy config for CRI-O
  template:
    src: "{{ item }}.j2"
    dest: "/etc/crio/{{ item }}"
  with_items:
    - crio.conf
  notify: Start CRI-O