---
- name: Check if flux is installed
  stat:
    path: /usr/local/bin/flux
  register: flux

- name: Check if flux as bootstraped
  stat:
    path: flux_bootstrap_output.txt
  register: bootstrap

- name: Install flux binary
  shell: curl -s https://fluxcd.io/install.sh | bash
  when: not flux.stat.exists

- name: Install auto-completion
  shell: . <(flux completion bash)
  when: not flux.stat.exists

- name: Bootstrap project Flux for "{{ kubernetes_clustername }}"
  shell: |
    flux bootstrap github \
    --token-auth \
    --owner="{{ flux_github_owner }}" \
    --repository="{{ flux_github_repo }}" \
    --branch="{{ flux_github_branch }}" \
    --path="{{ flux_cluster_path }}" \
    --personal > flux_bootstrap_output.txt
  when: not bootstrap.stat.exists
  environment:
    GITHUB_TOKEN: "{{ flux_github_token }}"
