---
- name: Add needed kernel modules for cri-o and k8s
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Add br_netfilter config for kernel module
  copy: 
    dest: /etc/modules-load.d/br_netfilter.conf
    content: |
      br_netfilter
    owner: root
    group: root
    mode: 644

- name: Add custom sysctl config
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward 

- name: disable swap on host
  command: "swapoff -a"

- name: Set SELinux disabled mode
  selinux:
    state: disabled
  register: selinux_config_changed

- name: Reboot the server if SELinux config was changed
  ansible.builtin.reboot:
    reboot_timeout: 60
  when: selinux_config_changed.changed

- name: Wait for the server to become available after reboot
  ansible.builtin.wait_for_connection:
    timeout: 60
