---
- name: Add needed kernel modules for cri-o and k8s
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Add br_netfilter config for kernel module
  copy: 
    path: /etc/modules-load.d/br_netfilter.conf
    content: |
      br_netfilter
    owner: root
    group: root
    mode: 644

- name: Add custom sysctl config
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward 

- name: disable swap on host
  command: "swapoff -a"

- name: Set SELinux permisive mode
  selinux:
    policy: targeted
    state: permissive
